name = "telegram-video-forwarder"
main = "src/index.js"
compatibility_date = "2025-03-05"

[vars]
ADMIN_ID = "7383046042"
SOURCE_CHANNEL_ID = "-1003657533852"
SERVER_URL = "https://telegram-video-forwarder.your-username.workers.dev"

[[kv_namespaces]]
binding = "VIDEO_TOKENS"
id = "0f6b66dde48f49e495208eea976fb0e6"

[[d1_databases]]
binding = "DB"
database_name = "video-token-db"
database_id = "79906f8b-8e35-4189-b8b1-4fa9202f1734"
